version: '1.0'
stages:
  - prepare   
  - build
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'austinlparker/otel-todo'
    revision: master
    git: github    
  build_server_image:
    title: Building Server Docker Image
    stage: build
    type: build
    image_name: aparker/todo-server
    working_directory: ./server
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile  
    on_success:
      metadata:
        set:
          - '${{MyAppDockerImage.imageId}}':
            - CF_QUALITY: true
            - Performance: true
            - Latency: ".89" 
            - Test_Coverage: "83%"
            - JIRA: "https://codefresh-io.atlassian.net/browse/MKTG-12"
  build_client_image:
    title: Building Client Docker Image
    stage: build
    type: build
    image_name: aparker/todo-client
    working_directory: ./client
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile  
    on_success:
      metadata:
        set:
          - '${{MyAppDockerImage.imageId}}':
            - CF_QUALITY: true
            - Performance: true
            - Latency: ".89" 
            - Test_Coverage: "83%"
            - JIRA: "https://codefresh-io.atlassian.net/browse/MKTG-12"
  deploy_chart:
    image: 'codefresh/cfstep-helm:3.0.3'
    title: Deploying Helm chart
    stage: deploy
    environment:
      - CHART_REF=helm
      - RELEASE_NAME=otel-todo-prod
      - KUBE_CONTEXT=${{KUBE_CONTEXT}}
      - VALUE_image_pullPolicy=Always
      - VALUE_image_tag=${{CF_SHORT_REVISION}}
      - VALUE_buildID='${{CF_BUILD_ID}}'
      - VALUE_image_pullSecret=codefresh-generated-docker.io-dockerhub-default
      - VALUE_lightstepKey=${{LS_KEY}}