apiVersion: apps/v1
kind: Deployment
metadata:
  name: kspan
spec:
  selector:
    matchLabels:
      app: kspan
  template:
    metadata:
      labels:
        app: kspan
    spec:
      containers:
        - name: kspan
          image: docker.io/weaveworks/kspan:v0.0
          imagePullPolicy: IfNotPresent
          args: ["-otlp-addr", "otel-collector.default:4317"]


