---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    extensions:
      health_check: {}
      zpages:
        endpoint: "0.0.0.0:55679"
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "collector"
      logging:
      otlp:
        endpoint: "ingest.lightstep.com:443"
        compression: gzip
        headers:
          "lightstep-access-token": "{{ .Values.lightstepKey }}"
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          exporters: [logging, prometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8889"
spec:
  type: {{ .Values.collector.serviceType }}
  {{ if eq .Values.collector.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ .Values.collector.ip }}
  {{ end }}
  ports:
  - name: otlp # Default endpoint for OpenTelemetry receiver.
    port: 4317
    {{ if eq .Values.collector.serviceType "LoadBalancer" }}
    targetPort: {{ .Values.collector.grpcPort }}
    {{ end }}
  - name: otlp-http
    port: 55681
    {{ if eq .Values.collector.serviceType "LoadBalancer" }}
    targetPort: {{ .Values.collector.httpPort }}
    {{ else }}
    nodePort: {{ .Values.collector.httpPort }}
    {{ end }}
  - name: metrics # Default endpoint for querying metrics.
    port: 8889
  - name: healthz
    port: 55679
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector:0.23.0
        name: otel-collector
        env:
          - name: REDEPLOYED_AT
            value: "{{now}}"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 8889  # Default endpoint for querying metrics.
        - containerPort: 55681 # HTTP OTLP Endpoint
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol