apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-client
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_ENV_Server": "http://localhost:{{ .Values.serverOptions.nodePort }}"
      };
    })();