apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.client.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{ if eq .Values.ingress.enabled true }}
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_ENV_Server": "http://{{ .Values.ingress.staticIp }}/server",
        "VUE_APP_ENV_Collector": "http://{{ .Values.ingress.staticIp }}/v1/trace",
        "VUE_APP_ENV_ServerBase": "{{ .Values.ingress.staticIp }}"
      };
    })();
  {{ else }}
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_ENV_Server": "http://localhost:{{ .Values.server.targetPort }}",
        "VUE_APP_ENV_Collector": "http://localhost:30011/v1/trace",
        "VUE_APP_ENV_ServerBase": "localhost:{{ .Values.server.targetPort }}"
      };
    })();
  {{ end }}