apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          image: "{{ .Values.image.repository }}/todo-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 9000
          env:
          - name: MYSQL_HOST
            value: "{{ .Values.serverOptions.mysqlHost }}"
          - name: REDEPLOYED_AT
            value: "{{now}}"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 500Mi


