apiVersion: v1
kind: Service
metadata:
  name: todo-server
  labels:
    app.kubernetes.io/name: todo-server
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"   
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
  - name: todo-server
    port: 9000
    nodePort: {{ .Values.serverOptions.nodePort }}
