image:
  repository: docker.io/aparker
  tag: latest
  pullPolicy: IfNotPresent
client:
  name: todo-client
  serviceType: LoadBalancer
  targetPort: 80
  ip: 35.223.88.219
server:
  name: todo-server
  serviceType: LoadBalancer
  targetPort: 9000
  ip: 104.198.253.217
  replicas: 1
collector:
  serviceType: LoadBalancer
  ip: 34.72.217.76
mysql-server:
  mysqlUser: todouser
  mysqlPassword: todopw
  mysqlDatabase: todos
# if running locally, set this value here or on the helm command line
lightstepKey: 