ingress:
  enabled: true
  staticIpResourceName: oteltodo-ip
  staticIp: 34.120.230.249
image:
  repository: docker.io/aparker
  tag: latest
  pullPolicy: IfNotPresent
client:
  name: todo-client
  serviceType: NodePort
  targetPort: 8080
server:
  name: todo-server
  serviceType: NodePort
  targetPort: 9000
  mySqlHost: todo-mysql-server
mysql-server:
  mysqlUser: todouser
  mysqlPassword: todopw
  mysqlDatabase: todos
# if running locally, set this value here or on the helm command line
lightstepKey: 